apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/version: "0.1"
  name: backend
  namespace: gaia-frontend 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      containers:
      - image: 122.96.144.180:30080/frontend/hyperos_backend_demo:v0.0.1
        imagePullPolicy: IfNotPresent
        name: backend
      dnsPolicy: ClusterFirst
