apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: gaia-frontend
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 32500
